### PR TITLE
Support anonymous guests which don't need accounts-password.

### PR DESCRIPTION
**Pull request by brettle**
Add configuration option AccountsGuest.anonymous (default: false).
Use login handler to create user. This is required for anonymous guests
and has the advantage of avoiding an extra client/server round trip.
Add server test for removing anonymous guests.

### CODE REVIEW

**Comment by artwells** [comment]
I'm having trouble merging this with the latest, particularly around Meteor.methods.

Could you get the latest and merge?

**Comment by brettle** [comment]
Looks like you managed to get this merged. When I merged, I could just accept all of your merges.

**Comment by brettle** [comment]
Oops. I stand corrected... Now I see what you are referring to. Looking into it...

**Comment by brettle** [comment]
OK. Looks like the pull request should be mergeable now.

**Comment by artwells** [comment]
thanks!

**Pull request merged**
