### PR TITLE
Use brettle:accounts-patch-ui to support useraccounts suite.

### PR DESCRIPTION
**Pull request by brettle**

### CODE REVIEW

**Comment by brettle** [comment]
This PR now also includes support for use with `brettle:accounts-add-service` to address adding a service to an existing guest account as discussed in issue #5.

A demo app can be found in the ['with-accounts-guest' branch of the 'brettle/meteor-accounts-deluxe-demo repo](https://github.com/brettle/meteor-accounts-deluxe-demo/tree/with-accounts-guest).

**Comment by artwells** [comment]
Thanks @brettle 

I'm getting "ReferenceError: LoginState is not define" when running meteor test-packages.  Could you take a look.

Thanks

**Comment by brettle** [comment]
There were merge conflicts which might have caused the problem. Should work now. Let me know if it doesn't.

**Comment by artwells** [comment]
still getting " ReferenceError: LoginState is not defined" on meteor test-packages.

Does it work for you?

**Comment by brettle** [comment]
Yes, it works for me. I just did:

```sh
$ git clone git@github.com:artwells/meteor-accounts-guest.git
$ cd meteor-accounts-guest
$ meteor test-packages ./
```
and opened localhost;3000 and all the tests passed. No LoginState error in the browser console or the terminal.

Can you post the contents of `/tmp/meteor-test-*/.meteor/versions` while the `meteor test-packages ./` is running?

**Comment by artwells** [comment]
thanks for looking into this:

accounts-base@1.2.0
accounts-password@1.1.1
artwells:accounts-guest@0.1.12
artwells:queue@0.1.1
autoupdate@1.2.1
base64@1.0.3
binary-heap@1.0.3
blaze@2.1.2
blaze-tools@1.0.3
boilerplate-generator@1.0.3
bootstrap@1.0.1
brettle:accounts-login-state@0.0.2
brettle:accounts-patch-ui@0.0.1
callback-hook@1.0.3
check@1.0.5
ddp@1.1.0
deps@1.0.7
ejson@1.0.6
email@1.0.6
fastclick@1.0.3
geojson-utils@1.0.3
html-tools@1.0.4
htmljs@1.0.4
http@1.1.0
id-map@1.0.3
jquery@1.11.3_2
json@1.0.3
launch-screen@1.0.2
livedata@1.0.13
local-test:artwells:accounts-guest@0.1.12
local-test:artwells:queue@0.1.1
localstorage@1.0.3
logging@1.0.7
matb33:collection-hooks@0.7.15
meteor@1.1.6
meteor-platform@1.2.2
minifiers@1.1.5
minimongo@1.0.8
mobile-status-bar@1.0.3
mongo@1.1.0
npm-bcrypt@0.7.8_2
observe-sequence@1.0.6
ordered-dict@1.0.3
random@1.0.3
reactive-dict@1.1.0
reactive-var@1.0.5
reload@1.1.3
retry@1.0.3
routepolicy@1.0.5
service-configuration@1.0.4
session@1.1.0
sha@1.0.3
spacebars@1.0.6
spacebars-compiler@1.0.6
srp@1.0.3
templating@1.1.1
test-in-browser@1.0.7
tinytest@1.0.5
tracker@1.0.7
ui@1.0.6
underscore@1.0.3
url@1.0.4
webapp@1.2.0
webapp-hashing@1.0.3

**Comment by brettle** [comment]
Hmm. I'm not sure if it's the cause of the problem, but there are some diffs:

```diff
--- /tmp/meteor-test-runqsogxq/.meteor/versions	2015-09-10 21:42:55.332721000 -0700
+++ /home/brettle/tmp/artwells_versions	2015-09-12 16:17:14.930744925 -0700
@@ -1,6 +1,7 @@
 accounts-base@1.2.0
 accounts-password@1.1.1
 artwells:accounts-guest@0.1.12
+artwells:queue@0.1.1
 autoupdate@1.2.1
 base64@1.0.3
 binary-heap@1.0.3
@@ -27,8 +28,10 @@
 launch-screen@1.0.2
 livedata@1.0.13
 local-test:artwells:accounts-guest@0.1.12
+local-test:artwells:queue@0.1.1
 localstorage@1.0.3
 logging@1.0.7
+matb33:collection-hooks@0.7.15
 meteor@1.1.6
 meteor-platform@1.2.2
 minifiers@1.1.5
```

Where did `artwells:queue@0.1.1` and `matb33:collection-hooks` come from?

Can you try building/testing from a fresh clone of the github repo? Maybe you have uncommitted changes?

**Comment by artwells** [comment]
Damn, sorry.  Totally my fault.  Once I emptied my local packages, everything runs great.

**Comment by brettle** [comment]
Yay! Any idea what the exact issue was? If there was some sort of conflict or incompatibility between one of those other packages and `brettle:accounts-login-state`, I'd like to look into it.

**Comment by artwells** [comment]
I think I may have had some incompatible code in a local file.  I can be sure, at least, that there was no incompatibility with any other distributed package. Again, my apologies.

**Comment by brettle** [comment]
Great. Thanks!

**Pull request merged**
